"""Generate LLVM/Clang include data from the typed C ABI catalog."""

from __future__ import annotations

from pathlib import Path
import re

from abi.c.model import CAbiProject
from abi.c.model.project import CallingConvention, LocationPolicy
from engine.generation import (
    ArtifactGenerationContext,
    ArtifactGenerator,
    GeneratedArtifact,
    GeneratedArtifactSet,
)


_CALLING_CONV_OUTPUT = Path("BedrockGenCallingConv.td")
_CATALOG_OUTPUT = Path("BedrockGenCABI.inc")
_MACROS = (
    "BEDROCK_C_TYPE",
    "BEDROCK_C_CALLING_CONVENTION",
    "BEDROCK_C_REGISTER_CLASS",
    "BEDROCK_C_ARGUMENT_REGISTER",
    "BEDROCK_C_RESULT_REGISTER",
    "BEDROCK_C_VALUE_CLASS",
    "BEDROCK_C_VALUE_KIND",
    "BEDROCK_C_LOCATION_POLICY",
    "BEDROCK_C_PROMOTION",
    "BEDROCK_C_PRESERVATION_REGISTER",
    "BEDROCK_C_RUNTIME_HELPER",
    "BEDROCK_C_RUNTIME_PARAMETER",
    "BEDROCK_C_MEMORY_ORDER",
    "BEDROCK_C_MEMORY_ORDER_STEP",
    "BEDROCK_C_ATOMIC_LOWERING",
    "BEDROCK_C_ATOMIC_OPERATION",
    "BEDROCK_C_ATOMIC_INSTRUCTION",
)

_LLVM_RETURN_TYPES = {
    "GENERAL_SCALAR": ("i1", "i8", "i16", "i32", "i64"),
    "FLOAT_SCALAR": ("f32", "f64"),
    "VECTOR_VALUE": (
        "nxv16i8", "nxv8i16", "nxv4i32", "nxv2i64",
        "nxv8f16", "nxv4f32", "nxv2f64",
    ),
    "PREDICATE_VALUE": ("nxv16i1", "nxv8i1", "nxv4i1", "nxv2i1"),
}
_LLVM_RETURN_CLASS_ORDER = (
    "PREDICATE_VALUE", "VECTOR_VALUE", "FLOAT_SCALAR", "GENERAL_SCALAR"
)
_SPILLABLE_REGISTER_GROUPS = {"GPR", "FPR", "VECTOR", "PREDICATE"}


class Generator(ArtifactGenerator):
    """Project C ABI entities into LLVM-friendly generated includes."""

    def generate(self, context: ArtifactGenerationContext) -> GeneratedArtifactSet:
        project = context.require_provider("abi.c")
        if not isinstance(project, CAbiProject):
            raise TypeError("abi.c provider must be a CAbiProject")
        convention = project.calling_convention
        _validate_llvm_projection(project, convention)
        return GeneratedArtifactSet(
            (
                GeneratedArtifact(
                    _CALLING_CONV_OUTPUT,
                    _render_calling_convention(
                        project, convention, context.workspace
                    ),
                ),
                GeneratedArtifact(
                    _CATALOG_OUTPUT, _render_catalog(project, context.workspace)
                ),
            ),
            self.artifact_id,
        )


def _validate_llvm_projection(
    project: CAbiProject, convention: CallingConvention
) -> None:
    classes = {
        project.register_classes.resolve(reference).id
        for reference in convention.register_classes
    }
    required_classes = {"GENERAL", "FLOATING", "VECTOR", "PREDICATE"}
    if classes != required_classes:
        raise ValueError(
            f"{convention.source}: LLVM projection requires register classes "
            f"{sorted(required_classes)}, got {sorted(classes)}"
        )
    values = {
        project.value_classes.resolve(reference).id:
        project.value_classes.resolve(reference)
        for reference in convention.value_classes
    }
    missing = set(_LLVM_RETURN_TYPES) - set(values)
    if missing:
        raise ValueError(
            f"{convention.source}: LLVM return projection lacks value classes "
            f"{sorted(missing)}"
        )
    expected_result_classes = {
        "GENERAL_SCALAR": "GENERAL",
        "FLOAT_SCALAR": "FLOATING",
        "VECTOR_VALUE": "VECTOR",
        "PREDICATE_VALUE": "PREDICATE",
    }
    for value_id, class_id in expected_result_classes.items():
        policy = values[value_id].result
        actual = (
            "NONE" if policy.register_class is None
            else project.register_classes.resolve(policy.register_class).id
        )
        if policy.mode != "value" or policy.units != 1 or actual != class_id:
            raise ValueError(
                f"{values[value_id].source}: LLVM return projection expects "
                f"one {class_id} value register"
            )


def _render_calling_convention(
    project: CAbiProject, convention: CallingConvention, workspace
) -> str:
    classes = {
        project.register_classes.resolve(reference).id:
        project.register_classes.resolve(reference)
        for reference in convention.register_classes
    }
    value_classes = {
        project.value_classes.resolve(reference).id:
        project.value_classes.resolve(reference)
        for reference in convention.value_classes
    }
    lines = [
        "//===-- BedrockGenCallingConv.td - generated C ABI -------*- tablegen -*-===//",
        "//",
        "// Generated by spec/artifacts/llvm-c-abi. Do not edit.",
        "// The argument state machine consumes BedrockGenCABI.inc; TableGen owns",
        "// the declarative return and call-preserved register records below.",
        "//",
        "//===----------------------------------------------------------------------===//",
        "",
        "def RetCC_Bedrock : CallingConv<[",
        "  CCIfType<[i1, i8, i16], CCPromoteToType<i32>>,",
    ]
    return_rules: list[str] = []
    for value_id in _LLVM_RETURN_CLASS_ORDER:
        value_class = value_classes[value_id]
        result_register_class = value_class.result.register_class
        if result_register_class is None:
            raise ValueError(f"value class {value_class.id!r} has no result class")
        register_class = classes[
            project.register_classes.resolve(result_register_class).id
        ]
        types = ", ".join(_LLVM_RETURN_TYPES[value_id])
        registers = ", ".join(
            workspace.resolve(item).id for item in register_class.results
        )
        return_rules.append(
            f"  CCIfType<[{types}], CCAssignToReg<[{registers}]>>"
        )
    lines.extend(",\n".join(return_rules).splitlines())
    lines.extend(("]>;", ""))

    callee_saved = next(
        item for item in convention.preservation
        if item.disposition == "callee_saved"
    ).registers
    spillable = tuple(
        item for item in callee_saved
        if workspace.resolve(item).group in _SPILLABLE_REGISTER_GROUPS
    )
    lines.extend(_callee_saved_record("CSR_Bedrock_Save", spillable, workspace))
    lines.append("")
    lines.extend(
        (
            "// Non-allocatable architectural state is excluded from PEI spills but",
            "// remains present in the complete C ABI call-preserved mask.",
        )
    )
    lines.extend(_callee_saved_record("CSR_Bedrock", callee_saved, workspace))
    lines.append("")
    return "\n".join(lines)


def _callee_saved_record(name: str, registers, workspace) -> list[str]:
    names = [workspace.resolve(item).id for item in registers]
    lines = [f"def {name} : CalleeSavedRegs<", "  (add " + names[0] + ","]
    for index in range(1, len(names)):
        suffix = ")>;" if index == len(names) - 1 else ","
        lines.append(f"       {names[index]}{suffix}")
    return lines


def _render_catalog(project: CAbiProject, workspace) -> str:
    lines = [
        "//===-- BedrockGenCABI.inc - generated C ABI data --------*- C++ -*-===//",
        "//",
        "// Generated by spec/artifacts/llvm-c-abi. Do not edit.",
        "// Define any BEDROCK_C_* macro before including this file. Undefined",
        "// record-family macros default to no-ops and are removed afterwards.",
        "//",
        "//===----------------------------------------------------------------------===//",
        "",
        *_macro_defaults(),
    ]
    namespace = project.namespaces["base"]
    for entity_id in namespace.type_inventory.declared:
        item = namespace.types[entity_id]
        fixed = isinstance(item.size_bits, int)
        lines.append(
            "BEDROCK_C_TYPE(" + ", ".join((
                item.id, _c_string(item.spelling), _token(item.call_kind),
                "FIXED" if fixed else "SYMBOLIC",
                str(item.size_bits) if fixed else "0",
                _c_string("") if fixed else _c_string(str(item.size_bits)),
                str(item.alignment_bytes), _token(item.representation or "none"),
            )) + ")"
        )

    convention = project.calling_convention
    stack = convention.stack
    lines.append(
        "BEDROCK_C_CALLING_CONVENTION(" + ", ".join((
            workspace.resolve(stack.pointer).id, _token(stack.growth),
            str(stack.entry_alignment_bytes),
            str(stack.first_argument_offset_bytes),
            str(stack.argument_slot_bytes), workspace.resolve(stack.sret_register).id,
            str(stack.red_zone_bytes),
        )) + ")"
    )
    for reference in convention.register_classes:
        register_class = project.register_classes.resolve(reference)
        lines.append(
            f"BEDROCK_C_REGISTER_CLASS({register_class.id}, "
            f"{_token(register_class.allocation)}, "
            f"{register_class.tuple_alignment}, "
            f"{_token(register_class.exhaustion)})"
        )
        for index, register in enumerate(register_class.arguments):
            lines.append(
                f"BEDROCK_C_ARGUMENT_REGISTER({register_class.id}, {index}, "
                f"{workspace.resolve(register).id})"
            )
        for index, register in enumerate(register_class.results):
            lines.append(
                f"BEDROCK_C_RESULT_REGISTER({register_class.id}, {index}, "
                f"{workspace.resolve(register).id})"
            )
    for value_class_reference in convention.value_classes:
        value_class = project.value_classes.resolve(value_class_reference)
        lines.append(f"BEDROCK_C_VALUE_CLASS({value_class.id})")
        for kind in value_class.kinds:
            lines.append(f"BEDROCK_C_VALUE_KIND({value_class.id}, {_token(kind)})")
        lines.append(
            _location_line(project, value_class.id, "ARGUMENT", value_class.argument)
        )
        lines.append(
            _location_line(project, value_class.id, "RESULT", value_class.result)
        )
    for promotion_reference in convention.promotions:
        promotion = project.promotions.resolve(promotion_reference)
        for source_kind in promotion.source_kinds:
            lines.append(
                f"BEDROCK_C_PROMOTION({promotion.id}, {_token(source_kind)}, "
                f"{_token(promotion.target_kind)})"
            )
    for preservation in convention.preservation:
        for register in preservation.registers:
            lines.append(
                f"BEDROCK_C_PRESERVATION_REGISTER("
                f"{_token(preservation.disposition)}, {workspace.resolve(register).id})"
            )

    for entity_id in namespace.runtime_helper_inventory.declared:
        helper = namespace.runtime_helpers[entity_id]
        lines.append(
            f"BEDROCK_C_RUNTIME_HELPER({helper.id}, {_c_string(helper.symbol)}, "
            f"{project.types.resolve(helper.result).id})"
        )
        for index, parameter in enumerate(helper.parameters):
            lines.append(
                f"BEDROCK_C_RUNTIME_PARAMETER({helper.id}, {index}, "
                f"{project.types.resolve(parameter).id})"
            )

    for entity_id in namespace.memory_order_inventory.declared:
        mapping = namespace.memory_orders[entity_id]
        lines.append(
            f"BEDROCK_C_MEMORY_ORDER({mapping.id}, "
            f"{_token(mapping.instruction_order)}, "
            f"{int(mapping.load is not None)}, {int(mapping.store is not None)})"
        )
        for operation, sequence in (
            ("LOAD", mapping.load), ("STORE", mapping.store),
            ("THREAD_FENCE", mapping.thread_fence),
        ):
            for index, step in enumerate(sequence or ()):
                kind = "ACCESS" if step == "access" else "INSTRUCTION"
                value = (
                    "NONE"
                    if step == "access"
                    else workspace.resolve(step).instruction.mnemonic
                )
                lines.append(
                    f"BEDROCK_C_MEMORY_ORDER_STEP({mapping.id}, {operation}, "
                    f"{index}, {kind}, {value})"
                )

    for entity_id in namespace.atomic_lowering_inventory.declared:
        lowering = namespace.atomic_lowerings[entity_id]
        lines.append(
            f"BEDROCK_C_ATOMIC_LOWERING({lowering.id}, "
            f"{_token(lowering.strategy)})"
        )
        for operation in lowering.c_operations:
            lines.append(
                f"BEDROCK_C_ATOMIC_OPERATION({lowering.id}, {_token(operation)})"
            )
        for index, instruction in enumerate(lowering.instructions):
            lines.append(
                f"BEDROCK_C_ATOMIC_INSTRUCTION({lowering.id}, {index}, "
                f"{workspace.resolve(instruction).instruction.mnemonic})"
            )
    lines.extend(_macro_cleanup())
    lines.append("")
    return "\n".join(lines)


def _location_line(
    project: CAbiProject, value_class: str, direction: str, policy: LocationPolicy
) -> str:
    register_class = (
        "NONE"
        if policy.register_class is None
        else project.register_classes.resolve(policy.register_class).id
    )
    return (
        f"BEDROCK_C_LOCATION_POLICY({value_class}, {direction}, "
        f"{_token(policy.mode)}, {register_class}, {policy.units or 0}, "
        f"{policy.alignment_units}, {policy.direct_maximum_bytes or 0}, "
        f"{_token(policy.fallback or 'none')})"
    )


def _macro_defaults() -> list[str]:
    lines: list[str] = []
    for macro in _MACROS:
        marker = f"BEDROCK_GEN_DEFINED_{macro}"
        lines.extend((
            f"#ifndef {macro}", f"#define {macro}(...)",
            f"#define {marker}", "#endif",
        ))
    lines.append("")
    return lines


def _macro_cleanup() -> list[str]:
    lines = [""]
    for macro in _MACROS:
        marker = f"BEDROCK_GEN_DEFINED_{macro}"
        lines.extend((
            f"#ifdef {marker}", f"#undef {macro}",
            f"#undef {marker}", "#endif",
        ))
    return lines


def _token(value: str) -> str:
    token = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()
    if not token or token[0].isdigit():
        token = "VALUE_" + token
    return token


def _c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


__all__ = ["Generator"]
