#!/usr/bin/env python3
"""Generate ISA-reference tables owned by the architecture-table manifest."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys
from typing import Any, Iterable

try:
    import yaml
except ImportError as exc:  # pragma: no cover - environment error path
    raise SystemExit("PyYAML is required to generate architecture tables") from exc

from latex_builder.common import latex_longtable, latex_tabular, tex_code, tex_escape


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "isa" / "reference" / "architecture_tables.yaml"
FRAGMENT_DIR = ROOT / "isa" / "tools" / "latex_builder" / "templates" / "fragments"
GENERATED_DIR = FRAGMENT_DIR / "generated"
OPERANDS_SOURCE = ROOT / "isa" / "defs" / "operands.yaml"
RDPMC_TEMPLATE = ROOT / "isa" / "defs" / "instructions" / "RDPMC" / "details.tex.in"
RDPMC_OUTPUT = ROOT / "isa" / "defs" / "instructions" / "RDPMC" / "details.tex"
FPTRANSA_INSTRUCTION_DIR = (
    ROOT
    / "isa"
    / "defs"
    / "extensions"
    / "fpu"
    / "extensions"
    / "transcendental_approx"
    / "instructions"
)

GENERATED_HEADER = (
    "% Generated by isa/tools/gen_architecture_tables.py; do not edit.\n"
    "% Source: isa/reference/architecture_tables.yaml\n"
)


def load_mapping(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as stream:
        value = yaml.safe_load(stream)
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected a mapping")
    return value


def require_list(value: Any, context: str) -> list[dict[str, Any]]:
    if not isinstance(value, list) or not value:
        raise ValueError(f"{context}: expected a non-empty list")
    if not all(isinstance(item, dict) for item in value):
        raise ValueError(f"{context}: every entry must be a mapping")
    return value


def unique_values(entries: Iterable[dict[str, Any]], key: str, context: str) -> None:
    seen: set[Any] = set()
    for entry in entries:
        value = entry.get(key)
        if value in seen:
            raise ValueError(f"{context}: duplicate {key} {value!r}")
        seen.add(value)


def validate_manifest(data: dict[str, Any]) -> None:
    expected_keys = {
        "schema_version",
        "performance_counters",
        "reserved_field_defaults",
        "cpuid",
        "control_registers",
        "exception_causes",
        "fptransa_accuracy_contracts",
        "event_frames",
        "immediate_operand_interpretation",
        "reset_state",
        "atomic_memory_orders",
    }
    if data.get("schema_version") != 0:
        raise ValueError(f"{SOURCE}: schema_version must be 0")
    unknown = set(data) - expected_keys
    missing = expected_keys - set(data)
    if unknown or missing:
        raise ValueError(f"{SOURCE}: top-level keys differ: missing={sorted(missing)}, unknown={sorted(unknown)}")

    counters = require_list(data["performance_counters"], "performance_counters")
    unique_values(counters, "id", "performance_counters")
    unique_values(counters, "name", "performance_counters")
    if [int(item["id"]) for item in counters] != list(range(1, len(counters) + 1)):
        raise ValueError("performance_counters: standard IDs must be contiguous from one")

    controls = require_list(data["control_registers"], "control_registers")
    unique_values(controls, "selector", "control_registers")
    unique_values(controls, "name", "control_registers")
    if [int(item["selector"]) for item in controls] != sorted(int(item["selector"]) for item in controls):
        raise ValueError("control_registers: selectors must be in ascending order")

    causes = data["exception_causes"]
    if not isinstance(causes, dict) or set(causes) != {
        "PAGE_FAULT",
        "ILLEGAL_INSTRUCTION",
        "INVALID_CONTROL_STATE",
    }:
        raise ValueError("exception_causes: expected the three architected cause spaces")
    for exception, raw_entries in causes.items():
        entries = require_list(raw_entries, f"exception_causes.{exception}")
        unique_values(entries, "value", f"exception_causes.{exception}")
        unique_values(entries, "name", f"exception_causes.{exception}")
        values = [int(item["value"]) for item in entries]
        if values != list(range(len(values))):
            raise ValueError(f"exception_causes.{exception}: values must be contiguous from zero")

    cpuid = data["cpuid"]
    if not isinstance(cpuid, dict):
        raise ValueError("cpuid: expected a mapping")
    classes = require_list(cpuid.get("classes"), "cpuid.classes")
    unique_values(classes, "id", "cpuid.classes")
    leaf_by_selector: dict[tuple[int, int], dict[str, Any]] = {}
    for cls in classes:
        leaves = require_list(cls.get("leaves"), f"cpuid class {cls.get('id')}")
        unique_values(leaves, "id", f"cpuid class {cls.get('id')}")
        for leaf in leaves:
            leaf_by_selector[(int(cls["id"]), int(leaf["id"]))] = leaf

    contracts = require_list(data["fptransa_accuracy_contracts"], "fptransa_accuracy_contracts")
    unique_values(contracts, "id", "fptransa_accuracy_contracts")
    unique_values(contracts, "mnemonic", "fptransa_accuracy_contracts")
    contract_ids = [int(item["id"]) for item in contracts]
    if contract_ids != sorted(contract_ids) or any(value == 0 or value & 0xF == 0 for value in contract_ids):
        raise ValueError("fptransa_accuracy_contracts: IDs must be sorted, nonzero, and not family sentinels")
    fp_leaf = leaf_by_selector.get((1, 1))
    if fp_leaf is None or int(fp_leaf["max_index"]) != max(contract_ids):
        raise ValueError("cpuid: FPTRANSA_ACCURACY MAX_INDEX must equal the greatest contract ID")
    counter_leaf = leaf_by_selector.get((2, 2))
    if counter_leaf is None or int(counter_leaf["max_index"]) != max(int(item["id"]) for item in counters):
        raise ValueError("cpuid: PERFORMANCE_COUNTERS MAX_INDEX must equal the greatest standard counter ID")

    for contract in contracts:
        mnemonic = str(contract["mnemonic"])
        details_path = FPTRANSA_INSTRUCTION_DIR / mnemonic / "details.tex"
        if not details_path.is_file():
            raise ValueError(f"fptransa_accuracy_contracts: missing details for {mnemonic}")
        details = details_path.read_text(encoding="utf-8")
        expected = rf"contract is \texttt{{0x{int(contract['id']):04x}}}"
        if expected not in details:
            raise ValueError(f"{details_path}: expected {expected}")

    event_frames = data["event_frames"]
    if not isinstance(event_frames, dict):
        raise ValueError("event_frames: expected a mapping")
    frame_types = require_list(event_frames.get("types"), "event_frames.types")
    unique_values(frame_types, "code", "event_frames.types")
    unique_values(frame_types, "name", "event_frames.types")
    frame_names = {str(item["name"]) for item in frame_types}
    for frame in frame_types:
        total = int(frame["total_bytes"])
        allocated = int(frame["allocated_payload_bytes"])
        payload = int(frame["payload_bytes"])
        if total != 64 + allocated or allocated < payload or total % 8:
            raise ValueError(f"event_frames.types: inconsistent sizes for {frame['name']}")
    assignments = require_list(event_frames.get("assignments"), "event_frames.assignments")
    if any(str(item.get("frame_type")) not in frame_names for item in assignments):
        raise ValueError("event_frames.assignments: unknown frame type")

    operand_manifest = load_mapping(OPERANDS_SOURCE).get("operand_types")
    if not isinstance(operand_manifest, dict):
        raise ValueError(f"{OPERANDS_SOURCE}: operand_types must be a mapping")
    immediate_rows = require_list(
        data["immediate_operand_interpretation"], "immediate_operand_interpretation"
    )
    unique_values(immediate_rows, "operand_type", "immediate_operand_interpretation")
    for row in immediate_rows:
        operand_type = str(row["operand_type"])
        if operand_type not in operand_manifest:
            raise ValueError(f"immediate_operand_interpretation: unknown operand {operand_type}")

    orders = require_list(data["atomic_memory_orders"], "atomic_memory_orders")
    unique_values(orders, "selector", "atomic_memory_orders")
    unique_values(orders, "code", "atomic_memory_orders")
    declared_orders = operand_manifest.get("memory_order", {}).get("values", [])
    declared = [(item.get("name"), item.get("value")) for item in declared_orders]
    generated = [(item.get("selector"), item.get("code")) for item in orders]
    if generated != declared:
        raise ValueError("atomic_memory_orders: selectors must match operands.yaml memory_order values")


def code_list(values: Iterable[Any]) -> str:
    return ", ".join(tex_code(value) for value in values)


def generated(content: str) -> str:
    return GENERATED_HEADER + content.rstrip() + "\n"


def render_performance_counters(data: dict[str, Any]) -> str:
    effects = {
        "implementation_cycle_while_enabled": "each implementation cycle while PMC.EN is set",
        "committed_architectural_instruction": "each successfully committed architectural instruction",
        "hardware_page_walk_start_after_tlb_miss": "start of a hardware page walk after a paging-enabled TLB miss",
    }
    rows = [
        [tex_code(item["id"]), tex_code(item["name"]), tex_escape(effects[item["increment_event"]])]
        for item in data["performance_counters"]
    ]
    return latex_tabular(
        ["ID", "Name", "Increment event"],
        rows,
        ["0.55in", "1.05in", "3.80in"],
        "Standard Performance Counters",
    )


def render_reserved_defaults(data: dict[str, Any]) -> str:
    field_classes = {
        "architected_register_reserved_bits": "Architected register reserved bits",
        "control_register_reserved_bits": "Control-register reserved bits",
        "reserved_selector_values": "Reserved selector values",
        "consumed_reserved_pte_bits": "Consumed reserved PTE bits",
        "reserved_event_code_classes_or_ids": "Reserved event-code classes or IDs",
        "reserved_architectural_event_frame_bits": "Reserved architectural event-frame bits",
    }
    read_rules = {"zero": "zero", "unavailable": "--"}
    use_rules = {
        "must_be_zero": "must be zero",
        "invalid_selector": "invalid selector",
        "invalid_translation_input": "invalid translation input",
        "base_profile_must_not_generate": "must not be generated by the base profile",
    }
    rows = []
    for item in data["reserved_field_defaults"]:
        fault = item.get("fault")
        if fault == "INVALID_CONTROL_STATE_ON_ERET":
            fault_cell = tex_code("INVALID_CONTROL_STATE") + " on ERET"
        else:
            fault_cell = tex_code(fault) if fault else "--"
        rows.append(
            [
                tex_escape(field_classes[item["field_class"]]),
                tex_escape(read_rules[item["read_rule"]]),
                tex_escape(use_rules[item["use_rule"]]),
                fault_cell,
            ]
        )
    return latex_tabular(
        ["Field Class", "Read Rule", "Write or Use Rule", "Fault"],
        rows,
        ["1.65in", "0.75in", "1.35in", "1.65in"],
        "Reserved Field Defaults",
    )


def cpuid_max_index(value: Any) -> str:
    if isinstance(value, int):
        rendered = f"0x{value:04x}" if value >= 0x20 else str(value)
    else:
        rendered = str(value)
    return f"0..{rendered}"


def render_cpuid_directory(data: dict[str, Any]) -> str:
    rows: list[list[str]] = []
    for cls in data["cpuid"]["classes"]:
        rows.append(
            [
                tex_code(f"0x{int(cls['id']):08x}"),
                "--",
                rf"\textit{{{tex_escape(cls['name'])}}}",
                "--",
                tex_escape(cls["summary"]),
            ]
        )
        for leaf in cls["leaves"]:
            rows.append(
                [
                    tex_code(f"0x{int(cls['id']):08x}"),
                    tex_code(f"0x{int(leaf['id']):04x}"),
                    tex_code(leaf["name"]),
                    tex_code(cpuid_max_index(leaf["max_index"])),
                    tex_escape(leaf["summary"]),
                ]
            )
    return latex_longtable(
        ["Class", "Leaf", "Name", "Indexes", "Summary"],
        rows,
        ["0.82in", "0.62in", "1.35in", "0.70in", "1.90in"],
        "CPUID Class and Leaf Directory",
    )


def render_control_registers(data: dict[str, Any]) -> str:
    rows = [
        [tex_code(f"0x{int(item['selector']):04x}"), tex_code(item["name"]), tex_escape(item["use"])]
        for item in data["control_registers"]
    ]
    return latex_longtable(
        ["Selector", "Register", "Use"],
        rows,
        ["0.75in", "1.05in", "3.55in"],
        "Control-Register Selectors",
    )


def render_exception_causes(data: dict[str, Any], exception: str) -> str:
    rows = []
    for item in data["exception_causes"][exception]:
        meaning = tex_escape(item["meaning"])
        if item.get("address_type") == 0:
            meaning = "misaligned byte-addressed (" + tex_code("AT=0") + ") atomic operand"
        rows.append([tex_escape(item["value"]), tex_code(item["name"]), meaning])
    if exception == "PAGE_FAULT":
        headers = ["Value", "Cause", "Detection class"]
        widths = ["0.65in", "2.20in", "2.55in"]
    else:
        headers = ["Value", "Cause", "Meaning"]
        widths = ["0.65in", "2.35in", "2.40in"]
    return latex_tabular(headers, rows, widths, f"{exception} Causes")


REFERENCE_FUNCTIONS = {
    "sin": r"sin(x)",
    "cos": r"cos(x)",
    "tan": r"tan(x)",
    "sincos": r"paired sin(x) and cos(x)",
    "asin": r"asin(x)",
    "acos": r"acos(x)",
    "atan": r"atan(x)",
    "sinh": r"sinh(x)",
    "cosh": r"cosh(x)",
    "tanh": r"tanh(x)",
    "atanh": r"atanh(x)",
    "exp": r"$e^x$",
    "expm1": r"$e^x-1$ without an intermediate rounded exponential",
    "exp2": r"$2^x$",
    "exp10": r"$10^x$",
    "ln": r"ln(x)",
    "log1p": r"ln(1 + x) without an intermediate rounded addition",
    "log2": r"log2(x)",
    "log10": r"log10(x)",
}

DOMAINS = {
    "finite_abs_le_pi_over_4": r"finite x with abs(x) $\leq$ pi / 4 after DAZ",
    "finite_abs_le_one": r"finite x with abs(x) $\leq$ 1 after DAZ",
    "finite_or_signed_infinity": r"all finite values and signed infinity after DAZ",
    "positive_or_positive_infinity_zero_dz": (
        r"positive finite values and positive infinity after DAZ; signed zero is the DZ boundary"
    ),
    "finite_ge_minus_one_or_positive_infinity_minus_one_dz": (
        r"finite x $\geq -1$ and positive infinity after DAZ; $-1$ is the DZ boundary"
    ),
}


def render_fptransa_contracts(data: dict[str, Any]) -> str:
    rows = []
    for item in data["fptransa_accuracy_contracts"]:
        reference = REFERENCE_FUNCTIONS[item["function"]]
        if item.get("reference_qualifier") == "radians":
            reference += " in radians"
        max_ulp = item["max_ulp"]
        bound = rf"S $\leq$ {int(max_ulp['S'])} ULP; D $\leq$ {int(max_ulp['D'])} ULP"
        mnemonic = str(item["mnemonic"])
        rows.append(
            [
                tex_code(f"0x{int(item['id']):04x}"),
                rf"\hyperref[instr:{mnemonic.lower()}]{{{tex_code(mnemonic)}}}",
                reference,
                DOMAINS[item["domain"]],
                bound,
            ]
        )
    return latex_longtable(
        ["Contract ID", "Mnemonic", "Reference", "Domain", "ISA maximum"],
        rows,
        ["0.72in", "0.78in", "1.20in", "2.05in", "0.90in"],
        "FPTRANSA Accuracy Contracts",
    )


def render_event_frames(data: dict[str, Any]) -> str:
    rows = []
    for item in data["event_frames"]["types"]:
        last_slot = "none" if item["last_slot"] == "none" else tex_escape(item["last_slot"])
        rows.append(
            [
                f"0x{int(item['code']):x}",
                tex_escape(item["name"]),
                str(int(item["payload_bytes"])),
                str(int(item["allocated_payload_bytes"])),
                str(int(item["total_bytes"])),
                str(int(item["total_bytes"]) // 8),
                last_slot,
            ]
        )
    frame_table = latex_longtable(
        ["Code", "Type", "Payload", "Allocated", "Total", "Size", "Last slot"],
        rows,
        ["0.42in", "0.82in", "0.68in", "0.78in", "0.88in", "0.62in", "1.00in"],
        "Architectural Event Frame Types and Sizes",
    )
    assignment_rows = []
    for item in data["event_frames"]["assignments"]:
        if "events" in item:
            delivered = code_list(item["events"])
        else:
            delivered = "interrupt and NMI"
        assignment_rows.append([delivered, tex_escape(item["frame_type"])])
    assignment_table = latex_longtable(
        ["Delivered event", "Frame type"],
        assignment_rows,
        ["3.75in", "1.45in"],
        "Event-to-Frame-Type Assignment",
    )
    return frame_table + "\n" + assignment_table


def operand_range(spec: dict[str, Any], range_from: str) -> str:
    width = int(spec["field_width"])
    if range_from == "declared_values":
        values = [int(item["value"]) for item in spec.get("values", [])]
        if not values:
            raise ValueError("declared_values range requires enum values")
        return f"{min(values)}..{max(values)}"
    if range_from != "field_width":
        raise ValueError(f"unknown operand range source: {range_from}")
    return f"0..{(1 << width) - 1}"


def render_immediate_operands(data: dict[str, Any]) -> str:
    operands = load_mapping(OPERANDS_SOURCE)["operand_types"]
    rows = []
    for item in data["immediate_operand_interpretation"]:
        operand_type = str(item["operand_type"])
        spec = operands[operand_type]
        rows.append(
            [
                tex_code(operand_type),
                str(int(spec["field_width"])),
                tex_escape(item["value_kind"]),
                tex_escape(operand_range(spec, item["range_from"])),
                tex_escape(item["extension"]),
                tex_escape(item["applies_when"]),
            ]
        )
    return latex_longtable(
        ["Operand", "Bits", "Value", "Range", "Extension", "Applies When"],
        rows,
        ["0.95in", "0.38in", "0.62in", "0.62in", "0.90in", "1.70in"],
        "Immediate Operand Interpretation",
    )


def render_reset_state(data: dict[str, Any]) -> str:
    reset_values = {
        "zero": "0",
        "invalid": "invalid",
        "platform_supplied_cold_preserved_warm": "platform supplied on cold reset; preserved by warm RESET",
    }
    rows = []
    for item in data["reset_state"]:
        if "state_pairs" in item:
            state = ", ".join(f"{left}:{right}" for left, right in item["state_pairs"])
        else:
            names = [str(value) for value in item["state"]]
            state = ", ".join(names).replace("hidden_current_edepth", "hidden_current_edepth")
            state = state.replace("hidden_current_event_stack_level", "hidden current event stack level")
        rows.append([tex_escape(state), tex_escape(reset_values[item["value"]])])
    return latex_longtable(
        ["State", "Reset Value"],
        rows,
        ["2.00in", "2.40in"],
        "Architectural Reset State",
    )


def render_atomic_orders(data: dict[str, Any]) -> str:
    effects = {
        "atomicity_only": "Atomicity only. No ordering is imposed on unrelated memory operations.",
        "acquire": "Later memory operations by the same hardware thread are ordered after the atomic operation.",
        "release": "Earlier memory operations by the same hardware thread are ordered before the atomic operation.",
        "acquire_release": "Applies both acquire and release ordering.",
        "sequentially_consistent": (
            "Applies acquire-release ordering and participates in the single global sequentially consistent order."
        ),
    }
    rows = [
        [tex_code(item["selector"]), tex_code(item["code"]), tex_escape(effects[item["effect"]])]
        for item in data["atomic_memory_orders"]
    ]
    return latex_tabular(
        ["Selector", "Code", "Architectural Ordering Effect"],
        rows,
        ["0.95in", "0.45in", "4.00in"],
        "Atomic Memory-Order Selectors",
    )


def output_files(data: dict[str, Any]) -> dict[Path, str]:
    performance_table = render_performance_counters(data)
    if not RDPMC_TEMPLATE.is_file():
        raise ValueError(f"missing RDPMC template: {RDPMC_TEMPLATE}")
    rdpmc_details = RDPMC_TEMPLATE.read_text(encoding="utf-8")
    marker = "@STANDARD_PERFORMANCE_COUNTERS_TABLE@"
    if rdpmc_details.count(marker) != 1:
        raise ValueError(f"{RDPMC_TEMPLATE}: expected exactly one {marker}")
    rdpmc_details = rdpmc_details.replace(marker, performance_table.rstrip())

    return {
        GENERATED_DIR / "reserved_field_defaults.tex": generated(render_reserved_defaults(data)),
        GENERATED_DIR / "cpuid_class_leaf_directory.tex": generated(render_cpuid_directory(data)),
        GENERATED_DIR / "control_register_selectors.tex": generated(render_control_registers(data)),
        GENERATED_DIR / "page_fault_causes.tex": generated(render_exception_causes(data, "PAGE_FAULT")),
        GENERATED_DIR / "illegal_instruction_causes.tex": generated(
            render_exception_causes(data, "ILLEGAL_INSTRUCTION")
        ),
        GENERATED_DIR / "invalid_control_state_causes.tex": generated(
            render_exception_causes(data, "INVALID_CONTROL_STATE")
        ),
        GENERATED_DIR / "immediate_operand_interpretation.tex": generated(
            render_immediate_operands(data)
        ),
        GENERATED_DIR / "atomic_memory_order_selectors.tex": generated(render_atomic_orders(data)),
        FRAGMENT_DIR / "fptransa_accuracy_contracts.tex": generated(render_fptransa_contracts(data)),
        FRAGMENT_DIR / "frame_type_table.tex": generated(render_event_frames(data)),
        FRAGMENT_DIR / "reset_state_table.tex": generated(render_reset_state(data)),
        RDPMC_OUTPUT: generated(rdpmc_details),
    }


def generate(*, check: bool = False) -> list[Path]:
    data = load_mapping(SOURCE)
    validate_manifest(data)
    outputs = output_files(data)
    stale: list[Path] = []
    for path, content in outputs.items():
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the manifest and fail if generated files are stale",
    )
    args = parser.parse_args()
    stale = generate(check=args.check)
    if stale:
        for path in stale:
            print(f"stale generated architecture table: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
