from .core import SpecError, Pattern, PatternEntry, ValidationResult
from .loader import SPEC_FILES, load_yaml, load_yaml_with_includes, load_spec, normalize_loaded_spec
from .encoding import (
    bitmap_operand_ranges,
    compact_ea_values_by_name,
    condition_named_values,
    condition_names_by_value,
    condition_sleigh_checks,
    control_register_named_values,
    ea_segment_named_values,
    encoding_schema_errors,
    fflag_meanings,
    fflag_names,
    flag_names,
    flag_pseudo_registers,
    mnemonic_policy,
    named_values,
    named_value_width,
    prefix_value,
    register_names,
    size_code_bytes,
    size_code_label,
    size_kind_byte_widths,
    size_kind_field,
    size_kind_suffixes,
    size_kind_width,
    size_kinds,
    special_register_attach_names,
    special_register_encoding,
    special_register_layout,
    special_register_named_values,
)
from .catalog import instruction_catalog, normalized_family_catalog, family_section_entries
from .patterns import (
    cleaned_pattern,
    parse_pattern,
    patterns_overlap,
    pattern_dict,
    entry_dict,
    json_dumps,
    field_names,
    entry_id,
    aliases_for,
    overlap_allowed,
    length_bounds,
    operand_field_refs,
)
from .consistency import (
    validate_spec_consistency,
    check_overlaps,
    semantic_entry_mnemonics,
    catalog_sections,
    catalog_operand_schema,
    catalog_entry_map,
    entry_has_operand_profile,
    operand_forms_from_value,
    is_operand_spec,
)
