"""Generate LLVM/LLD include data from the typed ELF ABI catalog."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
import re

from abi.elf.model import ElfAbiProject, RelocationExpression
from abi.elf.model.project import Relocation
from engine.generation import (
    ArtifactGenerationContext,
    ArtifactGenerator,
    GeneratedArtifact,
    GeneratedArtifactSet,
)


_RELOCATIONS_OUTPUT = Path("ELFRelocs/Bedrock.def")
_CATALOG_OUTPUT = Path("BedrockGenELFABI.inc")

_LLD_EXPRESSION_SIGNATURES = {
    "(+ symbol addend)": "ABS",
    "copy(symbol,symbol_size)": "ABS",
    "resolver((+ load_base addend))": "ABS",
    "(+ load_base addend)": "ABS",
    "(- (+ symbol addend) place)": "PC",
    "(- (+ symbol addend) next_pc)": "PC",
    "(- (+ symbol addend) section_base)": "SECTION_REL",
    "(- (+ plt(symbol) addend) next_pc)": "PLT_PC",
    "(+ plt(symbol) addend)": "PLT",
    "(+ got(symbol) addend)": "GOT",
    "(- (+ got(symbol) addend) place)": "GOT_PC",
    "(- (+ symbol addend) got_base)": "GOTPLTREL",
    "(- (+ got_base addend) place)": "GOTPLTONLY_PC",
    "(+ tls(symbol) addend)": "TPREL",
    "(- (+ tlsdesc(symbol) addend) place)": "TLSDESC_PC",
    "tls_descriptor(symbol)": "TLSDESC",
}

_MACROS = (
    "BEDROCK_ELF_RELOCATION",
    "BEDROCK_ELF_RELAXATION",
    "BEDROCK_ELF_CODE_MODEL",
    "BEDROCK_ELF_CODE_MODEL_RELOCATION",
    "BEDROCK_ELF_TLS_MODEL",
    "BEDROCK_ELF_TLS_MODEL_RELOCATION",
    "BEDROCK_ELF_TLS_PROPERTY",
    "BEDROCK_ELF_LINKAGE_PROTOCOL",
    "BEDROCK_ELF_LINKAGE_STEP",
    "BEDROCK_ELF_LINKAGE_REGISTER",
    "BEDROCK_ELF_LINKAGE_PROPERTY",
    "BEDROCK_ELF_DEBUG_REGISTER_RANGE",
    "BEDROCK_ELF_DEBUG_REGISTER_MAPPING",
    "BEDROCK_ELF_ENTRY_STATE",
    "BEDROCK_ELF_ENTRY_STACK_PERMISSION",
    "BEDROCK_ELF_ENTRY_SEGMENT_CONTEXT",
    "BEDROCK_ELF_ENTRY_READINESS",
    "BEDROCK_ELF_ENTRY_CLEARED_REGISTER",
)


class Generator(ArtifactGenerator):
    """Project ELF ABI entities into LLVM-friendly X-macro includes."""

    def generate(self, context: ArtifactGenerationContext) -> GeneratedArtifactSet:
        project = context.require_provider("abi.elf")
        if not isinstance(project, ElfAbiProject):
            raise TypeError("abi.elf provider must be an ElfAbiProject")
        relocations = sorted(project.relocations.values(), key=lambda item: item.value)
        return GeneratedArtifactSet(
            (
                GeneratedArtifact(_RELOCATIONS_OUTPUT, _render_relocations(relocations)),
                GeneratedArtifact(
                    _CATALOG_OUTPUT,
                    _render_catalog(project, relocations, context.workspace),
                ),
            ),
            self.artifact_id,
        )


def _render_relocations(relocations: list[Relocation]) -> str:
    lines = [
        "//===-- Bedrock.def - generated ELF relocations ----------------*- C++ -*-===//",
        "//",
        "// Generated by spec/artifacts/llvm-elf-abi. Do not edit.",
        "//",
        "//===----------------------------------------------------------------------===//",
        "",
        '#ifndef ELF_RELOC',
        '#error "ELF_RELOC must be defined"',
        '#endif',
        "",
    ]
    lines.extend(f"ELF_RELOC({item.id}, {item.value})" for item in relocations)
    lines.append("")
    return "\n".join(lines)


def _render_catalog(project: ElfAbiProject, relocations: list[Relocation], workspace) -> str:
    lines = [
        "//===-- BedrockGenELFABI.inc - generated ELF ABI data --------*- C++ -*-===//",
        "//",
        "// Generated by spec/artifacts/llvm-elf-abi. Do not edit.",
        "// Define any BEDROCK_ELF_* macro before including this file to consume",
        "// that record family. Undefined macros default to no-ops.",
        "//",
        "// BEDROCK_ELF_RELOCATION(name, value, family, resultKind, widthBits,",
        "//                         isSigned, lldExpression, calculation, field)",
        "// BEDROCK_ELF_RELAXATION(source, target)",
        "// BEDROCK_ELF_CODE_MODEL(id, placement, strategy)",
        "// BEDROCK_ELF_CODE_MODEL_RELOCATION(model, relocation)",
        "// BEDROCK_ELF_TLS_MODEL(id, baseRegister, protocol, selection)",
        "// BEDROCK_ELF_TLS_MODEL_RELOCATION(model, relocation)",
        "// BEDROCK_ELF_TLS_PROPERTY(model, property, value)",
        "// BEDROCK_ELF_LINKAGE_PROTOCOL(id)",
        "// BEDROCK_ELF_LINKAGE_STEP(protocol, index, instruction, form, relocation)",
        "// BEDROCK_ELF_LINKAGE_REGISTER(protocol, disposition, register)",
        "// BEDROCK_ELF_LINKAGE_PROPERTY(protocol, property, value)",
        "// BEDROCK_ELF_DEBUG_REGISTER_RANGE(id, first, last, status, condition)",
        "// BEDROCK_ELF_DEBUG_REGISTER_MAPPING(id, number, register)",
        "// BEDROCK_ELF_ENTRY_STATE(pc, pcSource, sp, stackAlignment,",
        "//                         tlsBase, payloadOwner)",
        "// BEDROCK_ELF_ENTRY_STACK_PERMISSION(permission)",
        "// BEDROCK_ELF_ENTRY_SEGMENT_CONTEXT(role, register)",
        "// BEDROCK_ELF_ENTRY_READINESS(requirement)",
        "// BEDROCK_ELF_ENTRY_CLEARED_REGISTER(register)",
        "//",
        "//===----------------------------------------------------------------------===//",
        "",
    ]
    lines.extend(_macro_defaults())

    for relocation in relocations:
        result = relocation.result
        lines.append(
            "BEDROCK_ELF_RELOCATION("
            + ", ".join(
                (
                    relocation.id,
                    str(relocation.value),
                    _token(relocation.family or "none"),
                    _token(result.kind.value),
                    str(result.width_bits or 0),
                    "1" if result.signed else "0",
                    _lld_expression(relocation),
                    _c_string(relocation.calculation.code),
                    _c_string(str(relocation.field) if relocation.field else ""),
                )
            )
            + ")"
        )
        for target in relocation.relaxations:
            lines.append(
                f"BEDROCK_ELF_RELAXATION({relocation.id}, {target.element})"
            )

    for model in sorted(project.code_models.values(), key=lambda item: item.id):
        lines.append(
            f"BEDROCK_ELF_CODE_MODEL({model.id}, "
            f"{_c_string(str(model.data['placement']))}, "
            f"{_c_string(str(model.data['strategy']))})"
        )
        for relocation in model.default_relocations:
            lines.append(
                f"BEDROCK_ELF_CODE_MODEL_RELOCATION({model.id}, {relocation.element})"
            )

    for model in sorted(project.tls_models.values(), key=lambda item: item.id):
        base = "NONE" if model.base_register is None else model.base_register.local.element
        protocol = "NONE" if model.protocol is None else model.protocol.element
        lines.append(
            f"BEDROCK_ELF_TLS_MODEL({model.id}, {base}, {protocol}, "
            f"{_c_string(str(model.data['selection']))})"
        )
        for relocation in model.relocations:
            lines.append(
                f"BEDROCK_ELF_TLS_MODEL_RELOCATION({model.id}, {relocation.element})"
            )
        lines.extend(
            _property_lines(
                "BEDROCK_ELF_TLS_PROPERTY",
                model.id,
                model.data,
                excluded={"id", "selection", "base_register", "protocol", "relocations"},
            )
        )

    for assignment in sorted(
        project.resolved_debug_registers(workspace), key=lambda item: item.first
    ):
        range_name = (
            f"RESERVED_{assignment.first}"
            if assignment.status == "reserved"
            else assignment.group
        )
        last = "UNBOUNDED" if assignment.last is None else str(assignment.last)
        lines.append(
            f"BEDROCK_ELF_DEBUG_REGISTER_RANGE({range_name}, "
            f"{assignment.first}, {last}, {_token(assignment.status)}, "
            f"{_c_string(assignment.condition or '')})"
        )
        for offset, register in enumerate(assignment.registers):
            lines.append(
                f"BEDROCK_ELF_DEBUG_REGISTER_MAPPING({range_name}, "
                f"{assignment.first + offset}, {register.local.element})"
            )

    state = project.process_entry
    tls_base = "NONE" if state.tls_base is None else state.tls_base.local.element
    lines.append(
            f"BEDROCK_ELF_ENTRY_STATE("
            f"{state.entry_point.local.element}, "
            f"{_c_string(state.entry_point_source)}, {state.stack.local.element}, "
            f"{state.stack_alignment_bytes}, {tls_base}, "
            f"{_c_string(state.payload_owner)})"
    )
    for permission in state.stack_permissions:
        lines.append(f"BEDROCK_ELF_ENTRY_STACK_PERMISSION({_token(permission)})")
    for role, register in state.segment_contexts.items():
        lines.append(
            f"BEDROCK_ELF_ENTRY_SEGMENT_CONTEXT({_token(role)}, "
            f"{register.local.element})"
        )
    for requirement in state.readiness:
        lines.append(f"BEDROCK_ELF_ENTRY_READINESS({_token(requirement)})")
    for register in state.cleared:
        lines.append(f"BEDROCK_ELF_ENTRY_CLEARED_REGISTER({register.local.element})")

    for protocol in sorted(
        project.linkage_protocols.values(), key=lambda item: item.id
    ):
        lines.append(f"BEDROCK_ELF_LINKAGE_PROTOCOL({protocol.id})")
        for index, step in enumerate(protocol.steps):
            form = _c_string(step.form or "")
            relocation = "NONE" if step.relocation is None else step.relocation.local.element
            lines.append(
                f"BEDROCK_ELF_LINKAGE_STEP({protocol.id}, {index}, "
                f"{step.instruction.local.element}, {form}, {relocation})"
            )
        for state in protocol.state:
            for register in state.registers:
                lines.append(
                    f"BEDROCK_ELF_LINKAGE_REGISTER({protocol.id}, "
                    f"{_token(state.disposition)}, {register.local.element})"
                )
        lines.extend(
            _property_lines(
                "BEDROCK_ELF_LINKAGE_PROPERTY",
                protocol.id,
                protocol.data,
                excluded={"id", "steps", "state"},
            )
        )

    lines.extend(_macro_cleanup())
    lines.append("")
    return "\n".join(lines)


def _lld_expression(relocation: Relocation) -> str:
    if relocation.id == "R_BEDROCK_NONE":
        return "NONE"
    if relocation.id == "R_BEDROCK_TLSDESC_CALL":
        return "TLSDESC_CALL"
    signature = _expression_signature(relocation.calculation.expression)
    try:
        return _LLD_EXPRESSION_SIGNATURES[signature]
    except KeyError as error:
        raise ValueError(
            f"{relocation.source}: no LLVM/LLD expression mapping for "
            f"{relocation.calculation.code!r} ({signature})"
        ) from error


def _expression_signature(expression: RelocationExpression) -> str:
    if expression.kind == "integer":
        assert expression.value is not None
        return str(expression.value)
    if expression.kind == "term":
        assert expression.name is not None
        return expression.name
    if expression.kind == "neg":
        return f"(- {_expression_signature(expression.operands[0])})"
    if expression.kind in {"add", "sub"}:
        operator = "+" if expression.kind == "add" else "-"
        return (
            f"({operator} {_expression_signature(expression.operands[0])} "
            f"{_expression_signature(expression.operands[1])})"
        )
    assert expression.kind == "call" and expression.name is not None
    operands = ",".join(_expression_signature(item) for item in expression.operands)
    return f"{expression.name}({operands})"


def _property_lines(
    macro: str,
    owner: str,
    data: Mapping[str, object],
    *,
    excluded: set[str],
) -> list[str]:
    lines: list[str] = []

    def visit(path: tuple[str, ...], value: object) -> None:
        if isinstance(value, Mapping):
            for key in sorted(value):
                visit((*path, str(key)), value[key])
            return
        if isinstance(value, list):
            for index, item in enumerate(value):
                visit((*path, str(index)), item)
            return
        key = _token("_".join(path))
        lines.append(f"{macro}({owner}, {key}, {_scalar(value)})")

    for key in sorted(data):
        if key not in excluded:
            visit((str(key),), data[key])
    return lines


def _macro_defaults() -> list[str]:
    lines: list[str] = []
    for macro in _MACROS:
        marker = f"BEDROCK_GEN_DEFINED_{macro}"
        lines.extend(
            (
                f"#ifndef {macro}",
                f"#define {macro}(...)",
                f"#define {marker}",
                "#endif",
            )
        )
    lines.append("")
    return lines


def _macro_cleanup() -> list[str]:
    lines = [""]
    for macro in _MACROS:
        marker = f"BEDROCK_GEN_DEFINED_{macro}"
        lines.extend(
            (
                f"#ifdef {marker}",
                f"#undef {macro}",
                f"#undef {marker}",
                "#endif",
            )
        )
    return lines


def _token(value: str) -> str:
    token = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()
    if not token or token[0].isdigit():
        token = "VALUE_" + token
    return token


def _scalar(value: object) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return _c_string(value)
    raise TypeError(f"ELF ABI property cannot be projected as a scalar: {value!r}")


def _c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


__all__ = ["Generator"]
