use crate::{
    AddressSpaceControl, EventControl, Flags, PageTableControl, SegmentRegister, SegmentRegisters,
    SegmentSelector, Status,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CpuRegisterSet {
    General,
    Segment,
    Control,
    FloatingPoint,
}

impl CpuRegisterSet {
    pub const fn label(self) -> &'static str {
        match self {
            Self::General => "General",
            Self::Segment => "Segment",
            Self::Control => "Control",
            Self::FloatingPoint => "FPU",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CpuRegister {
    General(usize),
    FloatingPoint(usize),
    Sp,
    Pc,
    Flags,
    Status,
    Segment(SegmentSelector),
    Ptcr,
    Ascr,
    Ecr,
    Spc,
    Scs,
    Sds,
    Urpc,
    Ursp,
    Urcs,
    Urds,
    Urss,
    Urctl,
    Epc,
    Ecs,
    Eds,
    Sss,
    Ssp,
    Iss,
    Isp,
    Fss,
    Fsp,
    Dss,
    Dsp,
    BootPc,
    BootCfg,
    Ptc,
    Pmc,
    FStatus,
    FFlags,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CpuRegisterInfo {
    pub name: &'static str,
    pub bits: u16,
    pub set: CpuRegisterSet,
    pub register: CpuRegister,
}

macro_rules! reg {
    ($name:literal, $set:ident, $register:expr) => {
        CpuRegisterInfo {
            name: $name,
            bits: 64,
            set: CpuRegisterSet::$set,
            register: $register,
        }
    };
}

pub const CPU_REGISTER_INFOS: &[CpuRegisterInfo] = &[
    reg!("R0", General, CpuRegister::General(0)),
    reg!("R1", General, CpuRegister::General(1)),
    reg!("R2", General, CpuRegister::General(2)),
    reg!("R3", General, CpuRegister::General(3)),
    reg!("R4", General, CpuRegister::General(4)),
    reg!("R5", General, CpuRegister::General(5)),
    reg!("R6", General, CpuRegister::General(6)),
    reg!("R7", General, CpuRegister::General(7)),
    reg!("R8", General, CpuRegister::General(8)),
    reg!("R9", General, CpuRegister::General(9)),
    reg!("R10", General, CpuRegister::General(10)),
    reg!("R11", General, CpuRegister::General(11)),
    reg!("R12", General, CpuRegister::General(12)),
    reg!("R13", General, CpuRegister::General(13)),
    reg!("R14", General, CpuRegister::General(14)),
    reg!("R15", General, CpuRegister::General(15)),
    reg!("SP", General, CpuRegister::Sp),
    reg!("PC", General, CpuRegister::Pc),
    CpuRegisterInfo {
        name: "FLAGS",
        bits: 16,
        set: CpuRegisterSet::General,
        register: CpuRegister::Flags,
    },
    CpuRegisterInfo {
        name: "STATUS",
        bits: 16,
        set: CpuRegisterSet::General,
        register: CpuRegister::Status,
    },
    reg!("CS", Segment, CpuRegister::Segment(SegmentSelector::Cs)),
    reg!("DS", Segment, CpuRegister::Segment(SegmentSelector::Ds)),
    reg!("SS", Segment, CpuRegister::Segment(SegmentSelector::Ss)),
    reg!("GS0", Segment, CpuRegister::Segment(SegmentSelector::Gs0)),
    reg!("GS1", Segment, CpuRegister::Segment(SegmentSelector::Gs1)),
    reg!("GS2", Segment, CpuRegister::Segment(SegmentSelector::Gs2)),
    reg!("GS3", Segment, CpuRegister::Segment(SegmentSelector::Gs3)),
    reg!("GS4", Segment, CpuRegister::Segment(SegmentSelector::Gs4)),
    reg!("GS5", Segment, CpuRegister::Segment(SegmentSelector::Gs5)),
    reg!("PTCR", Control, CpuRegister::Ptcr),
    reg!("ASCR", Control, CpuRegister::Ascr),
    reg!("ECR", Control, CpuRegister::Ecr),
    reg!("SPC", Control, CpuRegister::Spc),
    reg!("SCS", Control, CpuRegister::Scs),
    reg!("SDS", Control, CpuRegister::Sds),
    reg!("URPC", Control, CpuRegister::Urpc),
    reg!("URSP", Control, CpuRegister::Ursp),
    reg!("URCS", Control, CpuRegister::Urcs),
    reg!("URDS", Control, CpuRegister::Urds),
    reg!("URSS", Control, CpuRegister::Urss),
    reg!("URCTL", Control, CpuRegister::Urctl),
    reg!("EPC", Control, CpuRegister::Epc),
    reg!("ECS", Control, CpuRegister::Ecs),
    reg!("EDS", Control, CpuRegister::Eds),
    reg!("SSS", Control, CpuRegister::Sss),
    reg!("SSP", Control, CpuRegister::Ssp),
    reg!("ISS", Control, CpuRegister::Iss),
    reg!("ISP", Control, CpuRegister::Isp),
    reg!("FSS", Control, CpuRegister::Fss),
    reg!("FSP", Control, CpuRegister::Fsp),
    reg!("DSS", Control, CpuRegister::Dss),
    reg!("DSP", Control, CpuRegister::Dsp),
    reg!("BOOTPC", Control, CpuRegister::BootPc),
    reg!("BOOTCFG", Control, CpuRegister::BootCfg),
    reg!("PTC", Control, CpuRegister::Ptc),
    reg!("PMC", Control, CpuRegister::Pmc),
    reg!("F0", FloatingPoint, CpuRegister::FloatingPoint(0)),
    reg!("F1", FloatingPoint, CpuRegister::FloatingPoint(1)),
    reg!("F2", FloatingPoint, CpuRegister::FloatingPoint(2)),
    reg!("F3", FloatingPoint, CpuRegister::FloatingPoint(3)),
    reg!("F4", FloatingPoint, CpuRegister::FloatingPoint(4)),
    reg!("F5", FloatingPoint, CpuRegister::FloatingPoint(5)),
    reg!("F6", FloatingPoint, CpuRegister::FloatingPoint(6)),
    reg!("F7", FloatingPoint, CpuRegister::FloatingPoint(7)),
    reg!("F8", FloatingPoint, CpuRegister::FloatingPoint(8)),
    reg!("F9", FloatingPoint, CpuRegister::FloatingPoint(9)),
    reg!("F10", FloatingPoint, CpuRegister::FloatingPoint(10)),
    reg!("F11", FloatingPoint, CpuRegister::FloatingPoint(11)),
    reg!("F12", FloatingPoint, CpuRegister::FloatingPoint(12)),
    reg!("F13", FloatingPoint, CpuRegister::FloatingPoint(13)),
    reg!("F14", FloatingPoint, CpuRegister::FloatingPoint(14)),
    reg!("F15", FloatingPoint, CpuRegister::FloatingPoint(15)),
    CpuRegisterInfo {
        name: "FSTATUS",
        bits: 16,
        set: CpuRegisterSet::FloatingPoint,
        register: CpuRegister::FStatus,
    },
    CpuRegisterInfo {
        name: "FFLAGS",
        bits: 16,
        set: CpuRegisterSet::FloatingPoint,
        register: CpuRegister::FFlags,
    },
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CpuState {
    pub r: [u64; 16],
    pub f: [u64; 16],
    pub sp: u64,
    pub pc: u64,
    pub flags: Flags,
    pub status: Status,
    pub segments: SegmentRegisters,
    pub ptcr: PageTableControl,
    pub ascr: AddressSpaceControl,
    pub ecr: EventControl,
    pub spc: u64,
    pub scs: SegmentRegister,
    pub sds: SegmentRegister,
    pub urpc: u64,
    pub ursp: u64,
    pub urcs: SegmentRegister,
    pub urds: SegmentRegister,
    pub urss: SegmentRegister,
    pub urctl: u64,
    pub epc: u64,
    pub ecs: SegmentRegister,
    pub eds: SegmentRegister,
    pub sss: SegmentRegister,
    pub ssp: u64,
    pub iss: SegmentRegister,
    pub isp: u64,
    pub fss: SegmentRegister,
    pub fsp: u64,
    pub dss: SegmentRegister,
    pub dsp: u64,
    pub bootpc: u64,
    pub bootcfg: u64,
    pub ptc: u64,
    pub pmc: u64,
    pub fstatus: u16,
    pub fflags: u16,
    pub hidden_current_edepth: u8,
    pub hidden_current_esl: u8,
}

impl Default for CpuState {
    fn default() -> Self {
        Self {
            r: [0; 16],
            f: [0; 16],
            sp: 0,
            pc: 0,
            flags: Flags::empty(),
            status: Status::empty(),
            segments: SegmentRegisters::default(),
            ptcr: PageTableControl::disabled(),
            ascr: AddressSpaceControl::default(),
            ecr: EventControl::default(),
            spc: 0,
            scs: SegmentRegister::disabled(),
            sds: SegmentRegister::disabled(),
            urpc: 0,
            ursp: 0,
            urcs: SegmentRegister::disabled(),
            urds: SegmentRegister::disabled(),
            urss: SegmentRegister::disabled(),
            urctl: 0,
            epc: 0,
            ecs: SegmentRegister::disabled(),
            eds: SegmentRegister::disabled(),
            sss: SegmentRegister::disabled(),
            ssp: 0,
            iss: SegmentRegister::disabled(),
            isp: 0,
            fss: SegmentRegister::disabled(),
            fsp: 0,
            dss: SegmentRegister::disabled(),
            dsp: 0,
            bootpc: 0,
            bootcfg: 0,
            ptc: 0,
            pmc: 0,
            fstatus: 0,
            fflags: 0,
            hidden_current_edepth: 0,
            hidden_current_esl: 0,
        }
    }
}

impl CpuState {
    pub fn reset(&mut self, pc: u64) {
        *self = Self {
            pc,
            status: Status::PM,
            ..Self::default()
        };
    }
    pub fn read_register(&self, register: CpuRegister) -> u64 {
        match register {
            CpuRegister::General(i) => self.r[i],
            CpuRegister::FloatingPoint(i) => self.f[i],
            CpuRegister::Sp => self.sp,
            CpuRegister::Pc => self.pc,
            CpuRegister::Flags => u64::from(self.flags.bits()),
            CpuRegister::Status => u64::from(self.status.bits()),
            CpuRegister::Segment(s) => self.segments.get(s).raw(),
            CpuRegister::Ptcr => self.ptcr.raw(),
            CpuRegister::Ascr => self.ascr.raw(),
            CpuRegister::Ecr => self.ecr.raw(),
            CpuRegister::Spc => self.spc,
            CpuRegister::Scs => self.scs.raw(),
            CpuRegister::Sds => self.sds.raw(),
            CpuRegister::Urpc => self.urpc,
            CpuRegister::Ursp => self.ursp,
            CpuRegister::Urcs => self.urcs.raw(),
            CpuRegister::Urds => self.urds.raw(),
            CpuRegister::Urss => self.urss.raw(),
            CpuRegister::Urctl => self.urctl,
            CpuRegister::Epc => self.epc,
            CpuRegister::Ecs => self.ecs.raw(),
            CpuRegister::Eds => self.eds.raw(),
            CpuRegister::Sss => self.sss.raw(),
            CpuRegister::Ssp => self.ssp,
            CpuRegister::Iss => self.iss.raw(),
            CpuRegister::Isp => self.isp,
            CpuRegister::Fss => self.fss.raw(),
            CpuRegister::Fsp => self.fsp,
            CpuRegister::Dss => self.dss.raw(),
            CpuRegister::Dsp => self.dsp,
            CpuRegister::BootPc => self.bootpc,
            CpuRegister::BootCfg => self.bootcfg,
            CpuRegister::Ptc => self.ptc,
            CpuRegister::Pmc => self.pmc,
            CpuRegister::FStatus => u64::from(self.fstatus),
            CpuRegister::FFlags => u64::from(self.fflags),
        }
    }
    pub fn write_register(&mut self, register: CpuRegister, value: u64) {
        match register {
            CpuRegister::General(i) => self.r[i] = value,
            CpuRegister::FloatingPoint(i) => self.f[i] = value,
            CpuRegister::Sp => self.sp = value,
            CpuRegister::Pc => self.pc = value,
            CpuRegister::Flags => self.flags = Flags::from_bits_truncate(value as u16),
            CpuRegister::Status => self.status = Status::from_bits_truncate(value as u16),
            CpuRegister::Segment(s) => self.segments.set(s, SegmentRegister::from_raw(value)),
            CpuRegister::Ptcr => self.ptcr = PageTableControl::from_raw(value),
            CpuRegister::Ascr => self.ascr = AddressSpaceControl::from_raw(value),
            CpuRegister::Ecr => self.ecr = EventControl::from_raw(value),
            CpuRegister::Spc => self.spc = value,
            CpuRegister::Scs => self.scs = SegmentRegister::from_raw(value),
            CpuRegister::Sds => self.sds = SegmentRegister::from_raw(value),
            CpuRegister::Urpc => self.urpc = value,
            CpuRegister::Ursp => self.ursp = value,
            CpuRegister::Urcs => self.urcs = SegmentRegister::from_raw(value),
            CpuRegister::Urds => self.urds = SegmentRegister::from_raw(value),
            CpuRegister::Urss => self.urss = SegmentRegister::from_raw(value),
            CpuRegister::Urctl => self.urctl = value,
            CpuRegister::Epc => self.epc = value,
            CpuRegister::Ecs => self.ecs = SegmentRegister::from_raw(value),
            CpuRegister::Eds => self.eds = SegmentRegister::from_raw(value),
            CpuRegister::Sss => self.sss = SegmentRegister::from_raw(value),
            CpuRegister::Ssp => self.ssp = value,
            CpuRegister::Iss => self.iss = SegmentRegister::from_raw(value),
            CpuRegister::Isp => self.isp = value,
            CpuRegister::Fss => self.fss = SegmentRegister::from_raw(value),
            CpuRegister::Fsp => self.fsp = value,
            CpuRegister::Dss => self.dss = SegmentRegister::from_raw(value),
            CpuRegister::Dsp => self.dsp = value,
            CpuRegister::BootPc => self.bootpc = value,
            CpuRegister::BootCfg => self.bootcfg = value,
            CpuRegister::Ptc => self.ptc = value,
            CpuRegister::Pmc => self.pmc = value,
            CpuRegister::FStatus => self.fstatus = value as u16,
            CpuRegister::FFlags => self.fflags = value as u16,
        }
    }
}
